import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuBar from "./components/MenuBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={"min-h-screen flex flex-col"}
      >
        <header>
          <MenuBar/>
        </header>
        <main className="flex-grow p-4">
        {children}
        </main>
        <footer className="">
          <div>
            Im a footer
          </div>
        </footer>
      </body>
    </html>
  );
}
